### ISSUE TITLE
type : module

### ISSUE THREAD

**Issue by MasatoMakino** [MasatoMakino/threejs-spherical-controls#98]
three.jsおよびtween.jsがes moduleに移行したため、このモジュールも追従する。

**Comment by MasatoMakino** [comment]
tscでtype:"module"に対応した書き出しはできる。
jestで書き出したモジュールを読み込む場合、エラーが発生する。

```
  ● Test suite failed to run

    Cannot find module '@tweenjs/tween.js' from '__test__/AutoSphericalRotor.spec.ts'

    > 1 | import TWEEN, { Easing } from "@tweenjs/tween.js";
        | ^
      2 | import { RAFTicker } from "@masatomakino/raf-ticker";
      3 | import { AutoSphericalRotor } from "../src";
      4 | import { SleepWatcher, DragWatcher } from "@masatomakino/threejs-drag-watcher";

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (__test__/AutoSphericalRotor.spec.ts:1:1)
```

このパッケージ単体では問題が発生しないが、依存先のパッケージに影響を与える。
この問題が解決するまで、publishするバージョンからcjsを削除しないこととする。

jest以外のテスト環境を模索する。

**Comment by MasatoMakino** [comment]
移行先としてはvitestが候補。
jsdomも利用できる。

**Comment by MasatoMakino** [comment]
依存ツリー全体がesmに移行しないと、raf-tickerなどのモジュールがcjsとesmで分裂し、tickerが正常に働かなくなる。
移行は

- トップダウンで着手する
- 末端側はdual packagingに対応する

が望ましい
